services:
  logger:
    build: .
    ports:
      - "1123:1123"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/app/logs
      - ./keys:/app/keys:ro
      - ${HOME}/.pm2/pub.sock:/pm2.sock:ro
    environment:
      - LOGS_DIR=/app/logs
      - PORT=1123
      - PM2_SOCK=/pm2.sock
    restart: unless-stopped
